version: 2
jobs:
  build:
    docker:
      - image: alpine/git:1.0.4
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print remote branches
          command: git branch --list -r
