apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: mattermost
    app: mattermost
  name: mattermost
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mattermost
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: mattermost
    spec:
      containers:
      - image: mattermost
        name: mattermost
        resources: {}
status: {}
